name: bartech_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0

  # Reemplazar Isar con Drift
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.9.0

  provider: ^6.1.2

  # Agregar cached_network_image
  cached_network_image: ^3.3.1
  
  # Para configuración del servidor
  shared_preferences: ^2.2.2
  
  # Para reiniciar la app automáticamente
  restart_app: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  # Reemplazar isar_generator con drift_dev
  drift_dev: ^2.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/carrusel/
    - assets/loading1.gif
    - assets/choose/
    - assets/slider/
    - assets/products/